---
title: "Background_population"
author: "Morten"
format: html
editor: visual
---

## Background Population

For the study BHLL - representativeness Morten has been creating a dataset with background-population.

You can find the background population both named *stor_pop* (big population) and *DK5065* (Danes aged 50-65) at different places in this documentation as well as in existing programs.\

**Details**

The aim of the representatives study is to develop weights for the BHLL-cohort to make it more comparable with the background population, and to access this by comparing mortality in BHLL with mortality in background population.

The background population cohort (DK5065) is selected on similar criteria as BHLL-cohort:

-   50-65 years September 1st 2021.

-   Resident in Denmark 31dec2020.

-   Each individual is assigned an artificial index-date (distributed throughout autumn 2021 with same distribution as the BHLL-cohort). (Algortihm for this was developed by Istvan)

The BHLL-respondents is a subgroup within this population (except a very few who immigrated to Denmark in the period 01jan2021-30jun2021 - which I suggest excluding anyway, because we have limited background information on these - see "Help defining study population"...).

### **Usage in other BHLL-studies**

Besides using the cohort for the specific representativeness study, it can as well be used to add a little background information for most studies. E.g. a study in quality of life among stroke-survivors, can be supplemented with a table of prevalence of stroke-survivors in the background population, their medication use, comorbidities and their mortality.

### Representativenes results:

The very first results from representativenes study has been presented at ICPE Aug2024. [The poster can be downloaded here.](Representativeness%20ICPE2024%20final.pdf "Representativeness ICPE2024 final.pdf")

... More results (as well as weights for the BHLL-population) will follow...

## **For the statistician:**

The SAS-dataset can be found as **BHLLdata.stor_pop**.sas7bdat (older versions with date exists as well).

With the library BHLLdata pointing at: *E:\\ProjektDB\\KEA\\Workdata\\708194\\BHLL\\Studybase_prep\\BHLLprep_data\\*

The program creating the dataset is:

-   *E:\\ProjektDB\\KEA\\Workdata\\708194\\BHLL\\Studybase_prep\\03 stor_pop.sas*

Variables include:

-   **pnr**

-   **int_dato** (interview-date - for the BHLL cohort the actual date, for background population an artificial date with the same distribution during autumn 2021).

-   **BHLL**: 1 for BHLL-respondents, 0 for background population (who are not respondents). (Unfortunately it is not possible to identify those invited to the questionnaire, who didn't respond).

-   Relevant variables from **BEF**-dataset.

-   Information on mortality until end of 2022.

-   Information on whether 1yr of follow up in Danish registries is available (had been in DK for at least a year prior to int_dato)

*Return to [main BHLL-overview](main_ver01.html)*
