---
title: "MCS_PCS_PSS_MDI"
author: "MM"
format: html
editor: visual
---

## Official scores on BHLL (MCS, PCS, PSS, MDI)

One dataset with the four scores MCS, PCS, PSS and MDI for the BHLL-respondents can be found as:

E:\\ProjektDB\\KEA\\Workdata\\709876\\BHLL\\Studybase_prep\\BHLLprep_data\\scores.sasb7dat

And it is created by the program:

E:\\ProjektDB\\KEA\\Workdata\\709876\\Studybase_prep\\002 BHLL scores - MCS PCS PSS MDI ver2.sas

## About the scores:

### Physical Component Summary (PCS) and Mental Component Summary (MCS):

MCS and PCS has been officially scored from the SF-12 questions using software from Quality Metrics. And we have payed to be able to use questions and scores. (Cecilia was the KEA representatitve who made the agreement with Quality Metrics). If the SF-12 questions or MCS/PCS scores are used we should reference in the paper. In the cohort profile paper it is done by the following line: "Self-assessed health was evaluated using the 12-item short-form health survey known as SF12v2 (Quality Metric Incorporated, license no. QM053156)"

The full section on the scores in the cohort profile paper says:

"Some topics were addressed using previously validated questionnaires ([[Supplementary Table 1]{.underline}](https://www.dovepress.com/get_supplementary_file.php?f=436617.pdf)). For example, self-assessed health was evaluated using the 12-item short-form health survey known as SF12v2 (Quality Metric Incorporated, license no. QM053156)."

### Major Depression Inventory (MDI):

MDI is represented by two different variables (can be used in two different ways:

1.  The sum of the 10 questions can be summed up to a total score (theoretically ranging from 0-50). Varname: *MDI_score* \[what about missingness here???\]

2.  Evaluating the answers like the ICD-10 diagnostic criterion: Stored in the variable *MDI_depression*

Find [a more thorough description of the algorithm (especially for MDI_depression) here](MDI.html)

### Perceived Stress Scale (PSS):

PSS was calculated as a sum of the score of the individual questions.

[29.](https://www.dovepress.com/cohort-profile-better-health-in-late-life-peer-reviewed-fulltext-article-CLEP#ref-cit0029) Cohen S, Kamarck T, Mermelstein R. A global measure of **perceived stress**. *J Health Soc Behav*. 1983;24(4):385–396. doi:10.2307/2136404

The PSS measures the extent to which individuals perceive situations in their lives as stressful. The PSS has a theoretical score range from 0 to 40. No clinical cut-offs for PSS scores have been established.

Some prior BHLL-studies have grouped PSS into low (score of 0–13), moderate (score of 14–26), or high (score of 27–40).

##### Some methodological considerations on how to use PSS:

Dichotomization of the PSS-10 into “minimal” versus “moderate-to-high” stress, was based on a clinically oriented framework intended to enhance interpretability and align with prior literature, including previously published studies using the same approach (e.g. Viuff JH, Martiny SK, Fuglsang CH, et al. Self-rated health in venous thromboembolism survivors: a prevalence study. *J Thromb Haemost* 2025; 23: 2522-2530). We acknowledge that these thresholds are not formally validated and that categorization may reduce information.

We considered alternative model specifications. However, modeling PSS-10 as a continuous variable would require assumptions regarding the linearity and clinical interpretability of unit changes in perceived stress, for which there is limited established clinical meaning.

We agree that continuous modeling is generally preferable for maximizing statistical power, and this limitation has been acknowledged.

### Danish translations:

Regarding Danish translations of the different questions see: <https://www.dovepress.com/article/supplementary_file/436617/436617.pdf>

Edited: Morten Madsen 27/5-2025 and 27/2-2026

*Return to [main BHLL-overview](main_ver01.html)*
